### PR TITLE
Improve the instructions

### PR DESCRIPTION
**Pull request by mrksbrg**
- Restructured instructions
- Added an overview figure
- Various minor edits

### CODE REVIEW

**Comment by wogscpar** [comment]
I think it would be nice to actually link to the figures, as we have done with the titles.

**Comment by mrksbrg** [comment]
I agree, I'll add that. I think we'll only have one single figure (should be enough for now).

**Comment by mrksbrg** [comment]
Links added. I think this is good for now.

**Comment by wogscpar** [comment]
I agree :)

**Pull request merged**
