### PR TITLE
Readme updated to reflect the modification in the scripts

### PR DESCRIPTION
**Pull request by EFregnan**
The _README.md_ file has been modified to reflect the modifications done to _fetch.py_ and _git_to_to_array.py_

### CODE REVIEW

**Review by mrksbrg — CHANGES_REQUESTED** [review]
Thanks for updating the instructions to reflect the change! I noticed the discrepancy. Perhaps add example arguments that work for the Jenkins example? The first parameter has an example in fetch.py, but not the second one. It wouldn't hurt to repeat the example in the README.

**Comment by EFregnan** [comment]
Thank you for pointing this out. The _README.md_ file already contains examples of the parameters to use for the Jenkins project in the _fetch.py_ and _git_to_array.py_ scripts. They are stated at line 38 and 39.
However, I understand that they may be not really clear and easy to spot for the reader. 
An alternative could be to explicitly write an example of the scripts usage for Jenkins. Maybe in the format:
```python
python fetch.py --issue-code JENKINS --jira-project issues.jenkins-ci.org
```
Do you think this option would be better?

**Comment by mrksbrg** [comment]
Ah - yes, that's true. But I still support your recent suggestion. I think the explicit example you provided above would be helpful, it's surely not obvious in the current README.md. But adding such an example for fetch.py might require us to do the same for the others - for consistency.

I'm currently trying to improve the instructions in general. The goal is to make them foolproof of course, but I could also settle with reasonably understandable.

**Comment by wogscpar** [comment]
I guess that we could create a example directory where we put examples that reflects the Jenkins run? Then we can point the readers to that directory if they need further guidance.

**Comment by EFregnan** [comment]
I think it is a good idea. I can create an example directory with a Jenkins_example.md file in it, removing the example from the readme.md file. In this way, the user can find an example if he/she needs it, but without adding further lines of text to the readme.md file. I think this should help the readability as well. 

If you agree, I will close this pull request and I will open a new one with the above-mentioned modifications.

**Comment by mrksbrg** [comment]
I think that would be great. I think the example directory should also contain examples of what all different output files should look like. There are quite some steps involved, and it is hard to understand what is expected output (content-wise) from the scripts. This would be good for troubleshooting.

I vote for closing this PR and opening a new - my conflicting changes to README.md have anyway been merged already.

**Comment by wogscpar** [comment]
Great. Then I'm closing this. Or do you want to add something @EFregnan ?

**Comment by EFregnan** [comment]
Yes, you can close it. Thank you.

One last thing, I just realised that the _README_ file still doesn't contain an indication of the parameters to be used with _fetch.py_ and _git_log_to_array.py_. It needs something like this:

```python
python fetch.py --issue-code <issue_code> --jira-project <project_repository_name>
```

I will create a PR to fix only this small issue and then another one with the examples directory.

**Comment by wogscpar** [comment]
Great! I think we should write:
```bash
python fetch.py --issue-code <issues_code> --jira-project <jira_project_base_url>
```
Or something.

**Pull request closed without merging**
